#!/bin/bash
# Weekly cron entry point: regenerates docs/architecture-overview/ChainPilot-Architecture-Overview.pdf
# and commits it. The PDF file itself is always overwritten in place (no v1.pdf/v2.pdf pile-up) —
# only the version number printed inside the document advances.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PYTHON_BIN="/usr/local/bin/python3"
PDF_PATH="docs/architecture-overview/ChainPilot-Architecture-Overview.pdf"
VERSION_PATH="docs/architecture-overview/VERSION"

cd "$REPO_ROOT"

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting weekly architecture doc update"

"$PYTHON_BIN" scripts/development/update_architecture_doc.py

if [ -z "$(git status --porcelain -- "$PDF_PATH" "$VERSION_PATH")" ]; then
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] No changes to commit — architecture doc already up to date."
    exit 0
fi

VERSION="$(cat "$VERSION_PATH" 2>/dev/null || echo '?')"
git add "$PDF_PATH" "$VERSION_PATH"
git commit -m "docs: weekly architecture overview update (v${VERSION})" \
           -m "Auto-generated by scripts/development/weekly_architecture_update.sh" \
           -m "Co-Authored-By: Claude Sonnet 5 <noreply@anthropic.com>"

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Committed v${VERSION}"
